export const countries = [
  { name: 'United States', code: 'us' },
  { name: 'United Kingdom', code: 'gb' },
  { name: 'Canada', code: 'ca' },
  { name: 'Australia', code: 'au' },
  { name: 'Germany', code: 'de' },
  { name: 'France', code: 'fr' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'Sweden', code: 'se' },
  { name: 'Japan', code: 'jp' },
  { name: 'South Korea', code: 'kr' },
  { name: 'Singapore', code: 'sg' },
  { name: 'India', code: 'in' },
  { name: 'China', code: 'cn' },
  { name: 'Brazil', code: 'br' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Spain', code: 'es' },
  { name: 'Italy', code: 'it' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Belgium', code: 'be' },
  { name: 'Austria', code: 'at' },
  { name: 'Denmark', code: 'dk' },
  { name: 'Norway', code: 'no' },
  { name: 'Finland', code: 'fi' },
  { name: 'Ireland', code: 'ie' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Greece', code: 'gr' },
  { name: 'Poland', code: 'pl' },
  { name: 'Czech Republic', code: 'cz' },
  { name: 'Hungary', code: 'hu' },
  { name: 'Slovakia', code: 'sk' },
  { name: 'Slovenia', code: 'si' },
  { name: 'Croatia', code: 'hr' },
  { name: 'Bulgaria', code: 'bg' },
  { name: 'Romania', code: 'ro' },
  { name: 'Estonia', code: 'ee' },
  { name: 'Latvia', code: 'lv' },
  { name: 'Lithuania', code: 'lt' },
  { name: 'Luxembourg', code: 'lu' },
  { name: 'Malta', code: 'mt' },
  { name: 'Cyprus', code: 'cy' },
  { name: 'Iceland', code: 'is' },
  { name: 'New Zealand', code: 'nz' },
  { name: 'South Africa', code: 'za' },
  { name: 'Egypt', code: 'eg' },
  { name: 'Nigeria', code: 'ng' },
  { name: 'Kenya', code: 'ke' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Morocco', code: 'ma' },
  { name: 'Tunisia', code: 'tn' },
  { name: 'Algeria', code: 'dz' },
  { name: 'Ethiopia', code: 'et' },
  { name: 'Uganda', code: 'ug' },
  { name: 'Tanzania', code: 'tz' },
  { name: 'Rwanda', code: 'rw' },
  { name: 'Senegal', code: 'sn' },
  { name: 'Ivory Coast', code: 'ci' },
  { name: 'Cameroon', code: 'cm' },
  { name: 'Mali', code: 'ml' },
  { name: 'Burkina Faso', code: 'bf' },
  { name: 'Niger', code: 'ne' },
  { name: 'Chad', code: 'td' },
  { name: 'Sudan', code: 'sd' },
  { name: 'South Sudan', code: 'ss' },
  { name: 'Eritrea', code: 'er' },
  { name: 'Djibouti', code: 'dj' },
  { name: 'Somalia', code: 'so' },
  { name: 'Madagascar', code: 'mg' },
  { name: 'Mauritius', code: 'mu' },
  { name: 'Seychelles', code: 'sc' },
  { name: 'Comoros', code: 'km' },
  { name: 'Mauritania', code: 'mr' },
  { name: 'Gambia', code: 'gm' },
  { name: 'Guinea-Bissau', code: 'gw' },
  { name: 'Guinea', code: 'gn' },
  { name: 'Sierra Leone', code: 'sl' },
  { name: 'Liberia', code: 'lr' },
  { name: 'Togo', code: 'tg' },
  { name: 'Benin', code: 'bj' },
  { name: 'Equatorial Guinea', code: 'gq' },
  { name: 'Gabon', code: 'ga' },
  { name: 'Republic of the Congo', code: 'cg' },
  { name: 'Democratic Republic of the Congo', code: 'cd' },
  { name: 'Central African Republic', code: 'cf' },
  { name: 'Burundi', code: 'bi' },
  { name: 'Malawi', code: 'mw' },
  { name: 'Zambia', code: 'zm' },
  { name: 'Zimbabwe', code: 'zw' },
  { name: 'Botswana', code: 'bw' },
  { name: 'Namibia', code: 'na' },
  { name: 'Lesotho', code: 'ls' },
  { name: 'Eswatini', code: 'sz' },
  { name: 'Mozambique', code: 'mz' },
  { name: 'Angola', code: 'ao' },
  { name: 'Cape Verde', code: 'cv' },
  { name: 'São Tomé and Príncipe', code: 'st' },
  { name: 'Argentina', code: 'ar' },
  { name: 'Chile', code: 'cl' },
  { name: 'Peru', code: 'pe' },
  { name: 'Colombia', code: 'co' },
  { name: 'Venezuela', code: 've' },
  { name: 'Ecuador', code: 'ec' },
  { name: 'Bolivia', code: 'bo' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Uruguay', code: 'uy' },
  { name: 'Guyana', code: 'gy' },
  { name: 'Suriname', code: 'sr' },
  { name: 'French Guiana', code: 'gf' },
  { name: 'Falkland Islands', code: 'fk' },
  { name: 'Russia', code: 'ru' },
  { name: 'Ukraine', code: 'ua' },
  { name: 'Belarus', code: 'by' },
  { name: 'Moldova', code: 'md' },
  { name: 'Georgia', code: 'ge' },
  { name: 'Armenia', code: 'am' },
  { name: 'Azerbaijan', code: 'az' },
  { name: 'Kazakhstan', code: 'kz' },
  { name: 'Uzbekistan', code: 'uz' },
  { name: 'Turkmenistan', code: 'tm' },
  { name: 'Kyrgyzstan', code: 'kg' },
  { name: 'Tajikistan', code: 'tj' },
  { name: 'Mongolia', code: 'mn' },
  { name: 'North Korea', code: 'kp' },
  { name: 'Taiwan', code: 'tw' },
  { name: 'Hong Kong', code: 'hk' },
  { name: 'Macau', code: 'mo' },
  { name: 'Thailand', code: 'th' },
  { name: 'Vietnam', code: 'vn' },
  { name: 'Cambodia', code: 'kh' },
  { name: 'Laos', code: 'la' },
  { name: 'Myanmar', code: 'mm' },
  { name: 'Malaysia', code: 'my' },
  { name: 'Indonesia', code: 'id' },
  { name: 'Philippines', code: 'ph' },
  { name: 'Brunei', code: 'bn' },
  { name: 'East Timor', code: 'tl' },
  { name: 'Papua New Guinea', code: 'pg' },
  { name: 'Fiji', code: 'fj' },
  { name: 'Vanuatu', code: 'vu' },
  { name: 'Solomon Islands', code: 'sb' },
  { name: 'Kiribati', code: 'ki' },
  { name: 'Tuvalu', code: 'tv' },
  { name: 'Nauru', code: 'nr' },
  { name: 'Palau', code: 'pw' },
  { name: 'Marshall Islands', code: 'mh' },
  { name: 'Micronesia', code: 'fm' },
  { name: 'Samoa', code: 'ws' },
  { name: 'Tonga', code: 'to' },
  { name: 'Cook Islands', code: 'ck' },
  { name: 'Niue', code: 'nu' },
  { name: 'Tokelau', code: 'tk' },
  { name: 'American Samoa', code: 'as' },
  { name: 'Guam', code: 'gu' },
  { name: 'Northern Mariana Islands', code: 'mp' },
  { name: 'U.S. Virgin Islands', code: 'vi' },
  { name: 'Puerto Rico', code: 'pr' },
  { name: 'Greenland', code: 'gl' },
  { name: 'Iceland', code: 'is' },
  { name: 'Faroe Islands', code: 'fo' },
  { name: 'Åland Islands', code: 'ax' },
  { name: 'Svalbard and Jan Mayen', code: 'sj' },
  { name: 'Bouvet Island', code: 'bv' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'gs' },
  { name: 'French Southern Territories', code: 'tf' },
  { name: 'Heard Island and McDonald Islands', code: 'hm' },
  { name: 'British Indian Ocean Territory', code: 'io' },
  { name: 'Christmas Island', code: 'cx' },
  { name: 'Cocos (Keeling) Islands', code: 'cc' },
  { name: 'Norfolk Island', code: 'nf' },
  { name: 'Pitcairn Islands', code: 'pn' },
  { name: 'Wallis and Futuna', code: 'wf' },
  { name: 'French Polynesia', code: 'pf' },
  { name: 'New Caledonia', code: 'nc' },
  { name: 'Réunion', code: 're' },
  { name: 'Mayotte', code: 'yt' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', code: 'sh' },
  { name: 'Saint Pierre and Miquelon', code: 'pm' },
  { name: 'Bermuda', code: 'bm' },
  { name: 'Cayman Islands', code: 'ky' },
  { name: 'Turks and Caicos Islands', code: 'tc' },
  { name: 'Anguilla', code: 'ai' },
  { name: 'Montserrat', code: 'ms' },
  { name: 'British Virgin Islands', code: 'vg' },
  { name: 'Aruba', code: 'aw' },
  { name: 'Curaçao', code: 'cw' },
  { name: 'Sint Maarten', code: 'sx' },
  { name: 'Bonaire, Sint Eustatius and Saba', code: 'bq' },
  { name: 'Saint Martin', code: 'mf' },
  { name: 'Saint Barthélemy', code: 'bl' },
  { name: 'Guadeloupe', code: 'gp' },
  { name: 'Martinique', code: 'mq' },
  { name: 'Dominica', code: 'dm' },
  { name: 'Saint Lucia', code: 'lc' },
  { name: 'Saint Vincent and the Grenadines', code: 'vc' },
  { name: 'Barbados', code: 'bb' },
  { name: 'Grenada', code: 'gd' },
  { name: 'Trinidad and Tobago', code: 'tt' },
  { name: 'Antigua and Barbuda', code: 'ag' },
  { name: 'Saint Kitts and Nevis', code: 'kn' },
  { name: 'Jamaica', code: 'jm' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Dominican Republic', code: 'do' },
  { name: 'Cuba', code: 'cu' },
  { name: 'Bahamas', code: 'bs' },
  { name: 'Belize', code: 'bz' },
  { name: 'Guatemala', code: 'gt' },
  { name: 'El Salvador', code: 'sv' },
  { name: 'Honduras', code: 'hn' },
  { name: 'Nicaragua', code: 'ni' },
  { name: 'Costa Rica', code: 'cr' },
  { name: 'Panama', code: 'pa' },
  { name: 'Iran', code: 'ir' },
  { name: 'Iraq', code: 'iq' },
  { name: 'Syria', code: 'sy' },
  { name: 'Lebanon', code: 'lb' },
  { name: 'Jordan', code: 'jo' },
  { name: 'Israel', code: 'il' },
  { name: 'Palestine', code: 'ps' },
  { name: 'Saudi Arabia', code: 'sa' },
  { name: 'Yemen', code: 'ye' },
  { name: 'Oman', code: 'om' },
  { name: 'United Arab Emirates', code: 'ae' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Bahrain', code: 'bh' },
  { name: 'Kuwait', code: 'kw' },
  { name: 'Turkey', code: 'tr' },
  { name: 'Cyprus', code: 'cy' },
  { name: 'Greece', code: 'gr' },
  { name: 'Albania', code: 'al' },
  { name: 'North Macedonia', code: 'mk' },
  { name: 'Kosovo', code: 'xk' },
  { name: 'Serbia', code: 'rs' },
  { name: 'Montenegro', code: 'me' },
  { name: 'Bosnia and Herzegovina', code: 'ba' },
  { name: 'Croatia', code: 'hr' },
  { name: 'Slovenia', code: 'si' },
  { name: 'Hungary', code: 'hu' },
  { name: 'Slovakia', code: 'sk' },
  { name: 'Czech Republic', code: 'cz' },
  { name: 'Poland', code: 'pl' },
  { name: 'Lithuania', code: 'lt' },
  { name: 'Latvia', code: 'lv' },
  { name: 'Estonia', code: 'ee' },
  { name: 'Finland', code: 'fi' },
  { name: 'Sweden', code: 'se' },
  { name: 'Norway', code: 'no' },
  { name: 'Denmark', code: 'dk' },
  { name: 'Iceland', code: 'is' },
  { name: 'Ireland', code: 'ie' },
  { name: 'United Kingdom', code: 'gb' },
  { name: 'Netherlands', code: 'nl' },
  { name: 'Belgium', code: 'be' },
  { name: 'Luxembourg', code: 'lu' },
  { name: 'France', code: 'fr' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Austria', code: 'at' },
  { name: 'Germany', code: 'de' },
  { name: 'Italy', code: 'it' },
  { name: 'Spain', code: 'es' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Malta', code: 'mt' },
  { name: 'Vatican City', code: 'va' },
  { name: 'San Marino', code: 'sm' },
  { name: 'Monaco', code: 'mc' },
  { name: 'Liechtenstein', code: 'li' },
  { name: 'Andorra', code: 'ad' },
  { name: 'Gibraltar', code: 'gi' },
  { name: 'Other', code: '' },
];

export function getCountryCode(name: string): string | undefined {
  return countries.find((c) => c.name === name)?.code;
}
